/***********************************************************************/
/*                                                                     */
/*  FILE        :controller_model_cpp.cpp                              */
/*  DATE        :Thu, Oct 25, 2012                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :29                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#include "RotaryEncoder.hpp"
#include "MotorSpeed.hpp"

void main(void);

void main(void)
{
	SpeedMeter *speedMeter = new RotaryEncoder();
	MotorSpeed *motorSpeed = new MotorSpeed(speedMeter);
	
	speedMeter->getValue();
}
